"""Loads TTC's GTFS static feed (routes, stops, trips) into Postgres.

dim_route and dim_stop are SCD2 (slowly changing dimension, type 2): each
row has valid_from/valid_to/is_current, so a route or stop's history is
kept rather than overwritten -- if TTC ever renames a route or moves a
stop, the old version stays queryable instead of vanishing. dim_trip is a
plain full-refresh table instead: trip_id is regenerated by TTC on every
schedule publish, so there's no stable identity for SCD2 to track.

Run:
  docker compose -f compose.infra.yml run --rm gtfs-loader
"""

import csv
import io
import logging
import os
import sys
import zipfile

import psycopg2
import requests

GTFS_STATIC_URL = os.environ.get(
    "GTFS_STATIC_URL",
    "https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/"
    "7795b45e-e65a-4465-81fc-c36b9dfff169/resource/"
    "cfb6b2b8-6191-41e3-bda1-b175c51148cb/download/opendata_ttc_schedules.zip",
)

POSTGRES_DSN = (
    f"host={os.environ.get('POSTGRES_HOST', 'postgres')} "
    f"port={os.environ.get('POSTGRES_PORT', '5432')} "
    f"dbname={os.environ.get('POSTGRES_DB', 'serving')} "
    f"user={os.environ.get('POSTGRES_USER', 'ttc')} "
    f"password={os.environ.get('POSTGRES_PASSWORD', 'ttc_dev_password')}"
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s", stream=sys.stdout)
log = logging.getLogger("gtfs_static")

DDL = """
CREATE TABLE IF NOT EXISTS dim_route (
    route_key SERIAL PRIMARY KEY,
    route_id TEXT NOT NULL,
    route_short_name TEXT,
    route_long_name TEXT,
    route_type INTEGER,
    route_color TEXT,
    route_text_color TEXT,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_dim_route_current ON dim_route (route_id) WHERE is_current;

CREATE TABLE IF NOT EXISTS dim_stop (
    stop_key SERIAL PRIMARY KEY,
    stop_id TEXT NOT NULL,
    stop_code TEXT,
    stop_name TEXT,
    stop_lat DOUBLE PRECISION,
    stop_lon DOUBLE PRECISION,
    wheelchair_boarding INTEGER,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_dim_stop_current ON dim_stop (stop_id) WHERE is_current;

CREATE TABLE IF NOT EXISTS dim_trip (
    trip_id TEXT PRIMARY KEY,
    route_id TEXT,
    service_id TEXT,
    trip_headsign TEXT,
    direction_id INTEGER,
    shape_id TEXT,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""


def fetch_gtfs_zip(url: str) -> bytes:
    resp = requests.get(url, timeout=60)
    resp.raise_for_status()
    return resp.content


def read_csv_from_zip(zip_bytes: bytes, filename: str) -> list[dict]:
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as z:
        with z.open(filename) as f:
            return list(csv.DictReader(io.TextIOWrapper(f, encoding="utf-8-sig")))


def diff_scd2(current_rows: dict, new_rows: list[dict], key: str, tracked_fields: list[str]):
    """Compares the dimension's current rows against freshly parsed source
    rows. Returns (rows_to_insert, keys_to_expire) -- pure function, no DB,
    so this is the part that's actually unit tested."""
    to_insert = []
    to_expire = []
    new_by_key = {r[key]: r for r in new_rows}

    def norm(v):
        # `v or ""` would be wrong here: 0 and "0" are both legitimate GTFS
        # values (route_type 0 = streetcar) but 0 is falsy in Python, so
        # `0 or ""` silently becomes "" while `"0" or ""` stays "0" --
        # a false mismatch on every field that can legitimately be zero.
        return "" if v is None else str(v)

    for k, new_row in new_by_key.items():
        current = current_rows.get(k)
        if current is None:
            to_insert.append(new_row)
        elif any(norm(current.get(f)) != norm(new_row.get(f)) for f in tracked_fields):
            to_expire.append(k)
            to_insert.append(new_row)

    for k in current_rows:
        if k not in new_by_key:
            to_expire.append(k)

    return to_insert, to_expire


def get_current_rows(conn, table: str, key: str, tracked_fields: list[str]) -> dict:
    cols = [key] + tracked_fields
    with conn.cursor() as cur:
        cur.execute(f"SELECT {', '.join(cols)} FROM {table} WHERE is_current")
        return {row[0]: dict(zip(cols, row)) for row in cur.fetchall()}


def apply_scd2(conn, table: str, key: str, tracked_fields: list[str], new_rows: list[dict]):
    current = get_current_rows(conn, table, key, tracked_fields)
    to_insert, to_expire = diff_scd2(current, new_rows, key, tracked_fields)

    with conn.cursor() as cur:
        if to_expire:
            cur.execute(
                f"UPDATE {table} SET valid_to = now(), is_current = false "
                f"WHERE {key} = ANY(%s) AND is_current",
                (to_expire,),
            )
        for row in to_insert:
            cols = [key] + tracked_fields
            values = [row.get(c) or None for c in cols]
            placeholders = ", ".join(["%s"] * len(cols))
            cur.execute(
                f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({placeholders})",
                values,
            )
    conn.commit()
    log.info(f"{table}: {len(to_insert)} inserted, {len(to_expire)} expired, {len(current) - len(to_expire)} unchanged")


def load_trips(conn, rows: list[dict]):
    cols = ["trip_id", "route_id", "service_id", "trip_headsign", "direction_id", "shape_id"]
    with conn.cursor() as cur:
        cur.execute("TRUNCATE dim_trip")
        for row in rows:
            values = [row.get(c) or None for c in cols]
            placeholders = ", ".join(["%s"] * len(cols))
            cur.execute(f"INSERT INTO dim_trip ({', '.join(cols)}) VALUES ({placeholders})", values)
    conn.commit()
    log.info(f"dim_trip: full refresh, {len(rows)} trips loaded")


def main():
    log.info(f"Fetching GTFS static feed from {GTFS_STATIC_URL}")
    zip_bytes = fetch_gtfs_zip(GTFS_STATIC_URL)
    log.info(f"Downloaded {len(zip_bytes) / 1e6:.1f} MB")

    routes = read_csv_from_zip(zip_bytes, "routes.txt")
    stops = read_csv_from_zip(zip_bytes, "stops.txt")
    trips = read_csv_from_zip(zip_bytes, "trips.txt")
    log.info(f"Parsed {len(routes)} routes, {len(stops)} stops, {len(trips)} trips")

    conn = psycopg2.connect(POSTGRES_DSN)
    with conn.cursor() as cur:
        cur.execute(DDL)
    conn.commit()

    apply_scd2(
        conn, "dim_route", "route_id",
        ["route_short_name", "route_long_name", "route_type", "route_color", "route_text_color"],
        routes,
    )
    apply_scd2(
        conn, "dim_stop", "stop_id",
        ["stop_code", "stop_name", "stop_lat", "stop_lon", "wheelchair_boarding"],
        stops,
    )
    load_trips(conn, trips)

    conn.close()
    log.info("Done")


if __name__ == "__main__":
    main()
